### ISSUE TITLE
[idea] implement bigendian for MAD

### ISSUE THREAD

**Issue by lukaskuzmiak** [lukaskuzmiak/proxmark3#1]
See discussion here https://github.com/RfidResearchGroup/proxmark3/pull/763

**Comment by iceman1001** [comment]
Yes,   and while you at it,   in that pdf you linked,  they also talk about Cardholder information (3.5)
Also something that would be nice to present with the command if present.

**Comment by lukaskuzmiak** [comment]
@iceman1001 would you by any chance have a dump that contains `00 04` and textual data? I'm a bit worried to implement it "blind" :-)

**Comment by iceman1001** [comment]
Sorry, no I don't.   And I done much of my work blind ;)   Just go after the data sheet,   make a printline about "report issues to @iceman"  and wait until someone who has such a card reacts if there is any faults.   *easy*

**Comment by iceman1001** [comment]
@doegox just pushed ```hf mf mad --be```  to repo.   So only  that cardholder data left to do

**Comment by doegox** [comment]
Strangely, I had to force mad byte swapping on the `hf mf ndef` command to get a result...

**Comment by doegox** [comment]
ok that starts making sense. the NDEF AID was hardcoded in pm3 as 0x03e1, but official AID is 0xE103 so with that one we don't need that swap.
What a swap madness...

**Comment by lukaskuzmiak** [comment]
I have a good feeling about this, seems like all the pieces are coming together and it is according to the spec. yay!

**Comment by lukaskuzmiak** [comment]
Listed the cardholder information idea here: https://github.com/RfidResearchGroup/proxmark3/issues/767

Closing this.
